### ISSUE TITLE
Weekly Scrum - 2022/03/07

### ISSUE THREAD

**Issue by Imcool4789** [Imcool4789/Mini-SurveyMonkey#1]

**Comment by Imcool4789** [comment]
What have I done this week:
- Set up project to work with circleci and Heroku
- Contributed to the Question and Answer MVC
- Created Tests for Questions and answers models and controllers
- Set up MongoDB database to integrate in the next milestone
- Added ER/DB diagram

What will I do next week:
- Integrate MongoDB into project
- Create DB tests
- Implement capability to add answers into survey questions

What is holding me back:
- NOTHING YET

**Comment by Saxena-Kashish** [comment]
What have I done this week:

- Contributed to the Question MVC
- Created Tests for Questions Models and SurveyModel
- Contributed to creating and adding questions to survey

What will I do next week:

- Refactor Answer Model into different types
- Create remove question functionality
- Implement Answer Model tests
- Implement ability to close survey and return results

What is holding me back:

Nothing.

**Comment by vikiru** [comment]
What have I done this week:

- Setup local user login functionality for logging in as a surveyor or user with hard coded account information and different levels of permission. Surveyor can view the survey and create questions, while user can only view the survey. Can also logout once logged in
- Handled navigation through the app as surveyor and user via controllers, with the ability to alternate between the two after local logout
- Wrote simple html pages and some basic css for the html to show with certain redirects, two different form submissions handling is done via get and post method in controller for the relevant mapping (one form for login and one form for creating questions)
- Wrote tests for Login related controllers: SpringWebController, LoginController, SurveyorController, UserController
- Did major fixing of the repo, including a fix for adding questions into the survey and properly showing them in view survey page and also helped in re-organizing directories within main and test directories, ensuring all tests and functionality is working as intended for this milestone after fix
- Added Class UML Diagram
- Contributed to README writeup and formatting

What will I do next week:

- Integrate user login info storing via MongoDB and check credentials against the database
- Update surveyor ability to create questions and to have the option to create more than one question per page and proper question creation with the relevant option field (open ended text box, multiple choice options, and a text box to enter a range for number or a slider for numbers)
- Create results page

What is holding me back:
- There's a lot more I could have done via css styling to improve the look of the html pages, but I need more knowledge on css properties and I can definitely try to learn that for later milestones
