### ISSUE TITLE
Weekly Scrum March 21st

### ISSUE THREAD

**Issue by Imcool4789** [Imcool4789/Mini-SurveyMonkey#50]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- what is holding me back? (if applicable)

**Comment by vikiru** [comment]
What have I done this week:
- Updated Class UML Diagram
- Added NumberRangeAnswer model class and test
- Improved question creation functionality to now add options for a mc and number range question, directly utilizing JavaScript
- Set a plan for how I am going to use Google Charts API to generate Histogram and Pie Chart for Milestone 3
- Helped with general bug fixing
- Contributed to README updating

What will I do next week:
- Improve question creation functionality to handle multiple questions on same page
- Improve login functionality to utilize Spring Security
- Add a proper results page for each question with the respective result type - as is, histogram, pie chart
- Login related DB tests

What is holding me back:
- Need to look more into Thymeleaf conditional statements with various HTML elements, combining JavaScript with Thymeleaf templates will also improve functionality and I need to refresh my knowledge

**Comment by Saxena-Kashish** [comment]
What have I done this week:

- Implemented close survey functionality
- Implemented delete question functionality partially (still in progress)
- Refactored Answer Model to create open-ended answer model
- Wrote unit tests for open-ended answer model

What will I do next week:

- Complete delete question functionality
- Implement ability to return results after closing survey

What is holding me back:

- Need to learn more about adding more functionalities in the HTML pages

**Comment by Imcool4789** [comment]
what have I done this week?

- Modified AnswerController to add answers into survey
- Created MCAnswer Model
- Created HTML pages for each type of question (need more work, only open ended answer is working)
- Integrated MongoDB (Issues)
- Created MCAnswer Test
- Created Survey Answer Creation Test
- Fixed Bugs that came up

what will I do next week?

- Fully Integrate MongoDB
- Create MongoDB Tests
- Finish Survey Answer Creation for other answers (AnswerModel)
- Update Diagrams
- Implement Ability to add all types of answers to survey


what is holding me back?

- Ran into Authentication Errors while integrating db. Issue has been fixed but mongoDB will not be fully integrated until Milestone 3
